### ISSUE TITLE
uphound graphs

### ISSUE THREAD

**Issue by willkg** [paultag/snitch#4]
snitch is pretty neat in that it shows you data as of now. It'd be really super if it showed you historical data as well. Maybe with graphs/information similar to what uphound does:

https://www.uphound.com/

**Comment by paultag** [comment]
:+1:

**Comment by willkg** [comment]
Well, if you're going to thumbs-up that, I'm going to add another fantastic idea: when things are busted, it should go into a serious red alert mode. Like in this video:

https://www.youtube.com/watch?feature=player_detailpage&v=fMCV3KNYquo#t=55
